stages:
  - lint
#  - security
  - plan
  - apply

variables:
  TF_VERSION: "1.6.0"
  TF_IMAGE: opentofu/opentofu:${TF_VERSION}

# Étape pour TFLint (linting du code Terraform/Tofu)
tflint:
  image: ghcr.io/terraform-linters/tflint-binary:v0.44.0
  stage: lint
  script:
    - tflint --init
    - tflint

# Étape pour TFSec (scan de sécurité pour le code Terraform/Tofu)
#tfsec:
#  image: aquasec/tfsec:v1.28.1
#  stage: security
#  script:
#    - tfsec .

# Étape pour planifier les changements d'infrastructure (OpenTofu)
plan:
  image: ${TF_IMAGE}
  stage: plan
  script:
    - tofu init
    - tofu plan -out=tfplan
  artifacts:
    paths:
      - tfplan

# Étape pour appliquer les changements dans l'infrastructure (OpenTofu)
apply:
  image: ${TF_IMAGE}
  stage: apply
  script:
    - tofu apply -auto-approve tfplan
  when: manual
